org: dannytszho
app: aws-serverless-trails-api
service: aws-serverless-trails-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:Query"
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-trailsTable-${sls:stage}
  environment:
    DYNAMODB_TRAILS_TABLE: ${self:service}-trailsTable-${sls:stage}

custom:
  appSync:
    name: ${self:service}-appsync-${sls:stage}
    authenticationType: API_KEY
    schema:
      - src/graphql/schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: CustomerTable
        description: DynamoDB Table for trails
        config:
          tableName: ${self:provider.environment.DYNAMODB_TRAILS_TABLE} # Where MyTable is a dynamodb table defined in Resources

functions:
  graphqlHandler:
    handler: src/graphql/handler.graphqlHandler

  getTrailsList:
    handler: src/handlers.getTrailsList
    events:
      - httpApi:
          path: /rest
          method: get
  getTrail:
    handler: src/handlers.getTrail
    events:
      - httpApi:
          path: /{id}
          method: get
  createTrail:
    handler: src/handlers.createTrail
    events:
      - httpApi:
          path: /
          method: post
  updateTrail:
    handler: src/handlers.updateTrail
    events:
      - httpApi:
          path: /{id}
          method: put
  deleteTrail:
    handler: src/handlers.deleteTrail
    events:
      - httpApi:
          path: /{id}
          method: delete

resources:
  - ${file(./resources/dynamo-table.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-appsync-plugin
