Resources:
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: primary_key
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: primary_key
          KeyType: HASH
      TableName: ${self:service}-trailsTable-${sls:stage}
